#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $IRODS_ICAT_DBUSER WITH PASSWORD '$IRODS_ICAT_DBPASS';
    CREATE DATABASE "$IRODS_ICAT_DBNAME";
    GRANT ALL PRIVILEGES ON DATABASE "$IRODS_ICAT_DBNAME" TO $IRODS_ICAT_DBUSER;
EOSQL
