#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $ICAT_DB_USER WITH PASSWORD '$ICAT_DB_PASS';
    CREATE DATABASE "$ICAT_DB_NAME";
    GRANT ALL PRIVILEGES ON DATABASE "$ICAT_DB_NAME" TO irods;
EOSQL
